### ISSUE TITLE
Update first line in the colab demo

### ISSUE THREAD

**Issue by albusdemens** [submission6378/OneshotCLIP#3]
To avoid getting error messages when running the first cell of the [Colab notebook](https://github.com/anon96652/OneshotCLIP#testing-for-real-images), you should change the first code line to `!pip install tensorflow==1.15`.

**Comment by cyclomon** [comment]
Thanks! I updated the source code

**Comment by cyclomon** [comment]
Thank you, we revised the code following your recommendation.
