### ISSUE TITLE
Took norm twice while calculating Patch loss.

### ISSUE THREAD

**Issue by israrbacha** [submission6378/OneshotCLIP#4]
Hi mate,
Thanks for publicizing this exellent work. I skimmed through the code and found that you took norm twice while calculating the patch level contrastive loss here https://github.com/cyclomon/OneshotCLIP/blob/main/train_oneshot.py#L385 . Once right after calculating clip features here https://github.com/cyclomon/OneshotCLIP/blob/main/train_oneshot.py#L380 and then here  https://github.com/cyclomon/OneshotCLIP/blob/main/losses.py#L59 .   I am lil confused wether its experimental or any logic behind it? i also checked the MoCo loss which only use L_2 norm. I will appreciate your response.  Thanks!

**Comment by cyclomon** [comment]
Hi, this is just experimental, and I think removing one of the normalization may not severely change the output quality
